---

- name: Remove spotify repository
  ansible.builtin.apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: absent
    filename: spotify

- name: Remove spotify package
  ansible.builtin.apt:
    name: spotify-client
    update_cache: true
    state: absent

- name: Install spotify snap
  community.general.snap:
    name: spotify
    state: present
